### ISSUE TITLE
Maven downloads the whole internet

### ISSUE THREAD

**Issue by ptahchiev** [webjars/bootstrap#69]
Hello,
I'm opening this issue here, for lack of a better place to open it. 
This morning (February 22nd) I ran my maven build and it took 19 minutes and 44 seconds to download it's dependencies - nothing was changed since yesterday so I was expecting the built to take 15 seconds. It seems like I am downloading a TON of `npm` dependencies. At the end of the build it failed with the following error:
````
[ERROR] Failed to execute goal on project samplestore: Could not resolve dependencies for project com.nemesis.archetype:samplestore:war:2.0.0.BUILD-SNAPSHOT: Failed to collect dependencies at org.webjars.npm:magicsuggest:jar:2.1.4 -> org.webjars.npm:bootstrap:jar:4.0.0-alpha.3 -> org.webjars.npm:jquery:jar:3.3.0 -> org.webjars.npm:npm:jar:4.4.1 -> org.webjars.npm:npm-registry-client:jar:7.4.6 -> org.webjars.npm:semver:jar:2- >=2.2.1,[3,4),[4,5),[5,6): Failed to read artifact descriptor for org.webjars.npm:semver:jar:2- >=2.2.1,[3,4),[4,5),[5,6): Could not transfer artifact org.webjars.npm:semver:pom:2- >=2.2.1,[3,4),[4,5),[5,6) from/to spring-milestone (http://repo.spring.io/libs-milestone): Failed to transfer file: http://repo.spring.io/libs-milestone/org/webjars/npm/semver/2-%20%3E=2.2.1,%5B3,4),%5B4,5),%5B5,6)/semver-2-%20%3E=2.2.1,%5B3,4),%5B4,5),%5B5,6).pom. Return code is: 400 , ReasonPhrase:Bad Request. -> [Help 1]
````

Seems like magicsuggest:2.1.4 -> bootstrap:4.0.0-alpha.3 -> jquery 3.3.0 -> **npm** 4.4.1 -> ALL OF NPM

This looks weird because bootstrap 4.0.0-alpha.3 was uploaded 2016 to maven central:
view-source:http://repo1.maven.org/maven2/org/webjars/bootstrap/4.0.0-alpha.3/bootstrap-4.0.0-alpha.3.pom

But at the same time jquery 3.3.0 was uploaded exactly yesterday:
http://repo1.maven.org/maven2/org/webjars/npm/jquery/3.3.0/

Can someone please explain what is happening?

**Comment by jamesward** [comment]
Thanks for reporting.  Woah...  jQuery 3.3.0 has erroneous dependencies:
https://github.com/jquery/jquery/blob/3.3.0/package.json#L26-L31

Also I discovered that in your error there is a semver string that is not getting converted correctly:
https://github.com/npm/npm-registry-client/blob/v7.4.6/package.json#L25
https://search.maven.org/#artifactdetails%7Corg.webjars.npm%7Cnpm-registry-client%7C7.4.6%7Cjar

As a temporary workaround you can try to force jquery to resolve to `3.3.1` instead of `3.3.0`.

Welcome to the world of JavaScript package fun.  :)

**Comment by ptahchiev** [comment]
Any update here? I cannot build my project at all :(

**Comment by jamesward** [comment]
You'll need to override your dependency graph to use jquery `3.3.1` instead.

I am working on fixing the semver bug above but that alone won't fix your issue since the releases are immutable.

**Comment by jamesward** [comment]
I've released an updated `npm-registry-client` version `7.4.6-1` that has the correct version range.

**Comment by ptahchiev** [comment]
Hi @jamesward I'm really sorry but I don't consider this fixed. I once again tried my build with magicsuggest dependnency and this is the result:

https://gist.github.com/ptahchiev/8331d84e242ce831bb081c7214ff5edc

15 minutes!! This build usually lasts 40 seconds. 

As you can see this build downloads a ton of unneeded NPM webjars (I don't want them and they were not downloaded before, I don't understand why are they now downloaded as I have not changed anything in my pom.xml) and at the end if fails with:
```
No versions available for org.webjars.npm:spdx-exceptions:jar:[2.0.0,3) within specified range -> [Help 1]
```

**Comment by jamesward** [comment]
@ptahchiev Did you override the jquery dependency and verify it is resolving to `3.3.1`?

**Comment by ptahchiev** [comment]
@jamesward  I did not override anything :( I just ran `mvn clean compile`. It was working like this before so i figured out it should still work like this after your fix.

**Comment by jamesward** [comment]
The fix was for a bad SemVer range conversion so not directly related to your issue but uncovered by it.  Somewhere in your dep graph it is resolving to jquery `3.3.0` which pulls in the giant dependency tree.  You can sleuth out why that resolution is happening and walk up the tree to try to figure out where to change things to change the resolution to `3.3.1`.  Or you can just override the jquery dep.

**Comment by jamesward** [comment]
BTW, many NPM packages use version ranges which makes it hard to uncover why the graph is resolving in the way it is.  You can use a Maven plugin to explore this graph if you want to understand what is happening and why.
